### ISSUE TITLE
When two strings end with the same words, CreateWordDiffs includes the first common word as an insertion and deletion

### ISSUE THREAD

**Issue by tombogle** [mmanela/diffplex#91] opened 2022-02-28 21:16 UTC
DiffPlex.Differ.Instance.CreateWordDiffs("Am I a substring?", " a substring?", false, false, new [] ' ')
yields a result with a single DiffBlock:
DeleteCountA = 3
DeleteStartA = 0
InsertCountB = 1
InsertStartB = 0

I think the correct result should be
DeleteCountA = 2
DeleteStartA = 0
InsertCountB = 0
InsertStartB = 0

**Comment by tombogle** [comment] 2022-02-28 21:19
If I remove the leading space from the second argument, I get an even more bizarre result:
DiffPlex.Differ.Instance.CreateWordDiffs("Am I a substring?", "a substring?", false, false, new [] ' ')
yields a result with a single DiffBlock:
DeleteCountA = 4
DeleteStartA = 0
InsertCountB = 0
InsertStartB = 0

**Comment by mmanela** [comment] 2022-03-04 22:00
Thanks for the details. Part of this is by design (although its a bit confusing) and part of it is a bug that you found.

The way the chunking works in this case is that is will break up the words by those delimiters (in this case a space) but it will still include the delimiters as "words" in the diff. That is why the count is more than you expect, since it includes the spaces. The delimiters are just telling it how to align the words but you may still want to see if the delimiters are different. A future change could be to add a flag to ignore those.

As for the bug, you did find an issue where the string starts with a delimiter. I pushed a fix (ff1f16ba68442f6eed660de6f2fb2ccdc1d64d95) for this.

**Closed by mmanela** 2022-03-04 22:00 UTC

**Comment by tombogle** [comment] 2022-03-07 14:55
Thanks for the explanation and the fix.
